// ⚠️  REPLACE THIS FILE with your actual firebase_options.dart
// Generated by: flutterfire configure
// Run: flutterfire configure --project=YOUR_FIREBASE_PROJECT_ID

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  // 🔴 REPLACE with your actual Firebase config values from:

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHWfvTx9LzOKEWCd1frzy2n-4DwIuZc3g',
    appId: '1:914923583343:android:51b8e2560eddabaa35da9a',
    messagingSenderId: '914923583343',
    projectId: 'firebase-authentic',
    storageBucket: 'firebase-authentic.firebasestorage.app',
  );

  // Firebase Console → Project Settings → Your Apps

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.example.beastMode',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdHg0nYmjcmVgvPE3zVieOG8XS994YkYA',
    appId: '1:914923583343:web:0ceca6a1110707a035da9a',
    messagingSenderId: '914923583343',
    projectId: 'firebase-authentic',
    authDomain: 'fir-authentic-26208.firebaseapp.com',
    storageBucket: 'firebase-authentic.firebasestorage.app',
  );

}